name: Packagist

# on:
#   push:
#     tags:
#       - "*"

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - develop
      - feature/**

jobs:
  update-packagist:
    name: Update Packagist Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ "7.4" ]
    env:
      PACKAGIST_USER: ${{ secrets.PACKAGIST_USER }}
      PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CICD }}
      COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GH_TOKEN_CICD }}"} }'
    steps:
      - name: Run Packagist update script
        run: pwd && ls -la && bash ./scripts/update_packagist.sh
