name: Packagist

on:
  push:
    tags:
      - "*"

jobs:
  update-packagist:
    name: Update Packagist Version
    runs-on: ubuntu-latest
    env:
      PACKAGIST_USER: ${{ secrets.PACKAGIST_USER }}
      PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
    steps:
      - name: Run Packagist update script
        run: bash ./scripts/update_packagist.sh
