name: Packagist

# on:
#   push:
#     tags:
#       - "*"

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - develop
      - feature/**

jobs:
  update-packagist:
    name: Update Packagist Version
    runs-on: ubuntu-latest
    env:
      PACKAGIST_USER: ${{ secrets.PACKAGIST_USER }}
      PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
    steps:
      - name: Run Packagist update script
        run: pwd && ls -la && bash ./scripts/update_packagist.sh
